dist: xenial

env:
  - DOCKER_COMPOSE_VERSION: 1.23.1

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - chmod ugo+x ./dbench
  - chmod ugo+x ./test.sh
  - docker-compose up &
  - sleep 8m

script:
  - docker-compose ps | grep -i frappe | grep -i "Up|Healthy"
  - docker-compose ps | grep -i redis-cache | grep -i "Up|Healthy"
  - docker-compose ps | grep -i redis-queue | grep -i "Up|Healthy"
  - docker-compose ps | grep -i redis-socketio  | grep -i "Up|Healthy"
  - docker-compose ps | grep -i mariadb | grep -i "Up|Healthy"
  - ./test.sh
  - ./dbench setup docker stop
