version: '3.7'
services:
  mariadb:
    image: mariadb

    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root
    
    volumes:
      - ./conf/mariadb-conf.d:/etc/mysql/conf.d
      - /var/lib/mysql
    
    ports:
      - "3307:3306" #  Mariadb port
    
    networks:
      frappe:

  redis-cache:
    image: redis:alpine

    volumes:
        -./conf/redis-conf.d:/etc/conf.d

    networks:
      - frappe

    command: ["redis-server","/etc/conf.d/redis_cache.conf"]


  redis-queue:
    image: redis:alpine

    volumes:
        -./conf/redis-conf.d:/etc/conf.d

    networks:
      - frappe

    command: ["redis-server","/etc/conf.d/redis_queue.conf"]


  redis-socketio:
    image: redis:alpine

    volumes:
        -./conf/redis-conf.d:/etc/conf.d

    networks:
      - frappe

    command: ["redis-server","/etc/conf.d/redis_socketio.conf"]



  frappe:
    build: .
    volumes:
      - ./frappe-bench:/home/frappe/frappe-bench
      - ./conf/redis-conf/redis_cache.conf:/home/frappe/frappe-bench/config/redis_cache.conf
      - ./conf/redis-conf.d/redis_socketio.conf:/home/frappe/frappe-bench/config/redis_queue.conf
      - ./conf/redis-conf.d/redis_socketio.conf:/home/frappe/frappe-bench/config/redis_socketio.conf
    ports:
      - "8000:8000" # Webserver port
      - "9000:9000" # Socketio port
      - "6787:6787" # File Watcher port
    stdin_open: true
    tty: true
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio

    networks:
      - frappe
          

networks:
  frappe: